[project]
name = "ml-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pyeojim_pc", email = "pyeojim@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
ml-study = "ml_study:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
